### Импорт библиотек

In [2]:
import numpy as np
import random
random.seed(42) # начальное состояние генератора случайных чисел, чтобы можно было воспроизводить результаты.

### Возможные фунции активации и их производные

In [3]:
def sigmoid(x):
    """сигмоидальная функция, работает и с числами, и с векторами (поэлементно)"""
    return 1 / (1 + np.exp(-x))

def sigmoid_prime(x):
    """производная сигмоидальной функции, работает и с числами, и с векторами (поэлементно)"""
    return sigmoid(x) * (1 - sigmoid(x))

### Класс "Нейросеть"

In [194]:
class NeuralNetwork:
        
    def __init__(self, weights, a,  bias, activation_function=sigmoid):
        
        self.w = weights
        self.b = bias
        self.activation_function = activation_function
        self.a = a
        
    def summatory(self, x, w, b):
        w=np.array(w)
        return w.dot(x)+b
    
    def activation(self, z):   
        return self.activation_function(z)
    
    def vectorized_forward_pass(self, x):
        self.a[0]=x
        for i in range(1,self.a.shape[0]):
            self.a[i]=self.activation(self.summatory(self.a[i-1], self.w[i-1], self.b[i]))
        print('выходные активации:',self.a)
        
        
    def last_error(self, y):
        a=self.a[-1]
        return (a-y)*a*(1-a)
        
    def get_error(self, d, a, w):
        w=np.array(w)
        a=np.array(a)
        return (w.T.dot(d)*a*(1-a))
  
    def errors(self, y):
        d=self.last_error(y)
        print('последняя ошибка:',d)
        n=self.w.shape[0]
        for i in range(n-1,0,-1):
            d2=self.get_error(d,self.a[i],self.w[1])            
            self.w[i]-=d.dot(self.a[i].T)
            self.b[i+1]-=d
            d=d2
            print('ошибка:',d)
        self.w[0]-=d.dot(self.a[0].T)
        self.b[1]-=d
        print(-d.dot(self.a[0].T))

    '''
    def errors2(self, y):
        d=self.last_error(y)
        #d=-0.09146642
        print('последняя ошибка:',d)
        w=np.array(self.w[1][0])
        a=np.array(self.a[1])
        d21=w[0]*d
        d22=w[1]*d*a[1]*(1-a[1])
        print('ошибки:',d21, d22)
    '''

### Блок тестирования

In [196]:
y=np.array([[1]])
x=np.array([[0],[1],[1]])
w=np.array([[[0.7, 0.8, 0.7],[0.8, 0.3, 0.6]],[[0.2,0.4]]])
a=np.array([x,[[0],[0]],[[0]]])
b=np.array([[[0],[0],[0]],[[0],[0]],[[0]]])
NN=NeuralNetwork(w,a,b)
NN.vectorized_forward_pass(x)
NN.errors(y)

выходные активации: [array([[0],
       [1],
       [1]])
 array([[0.81757448],
       [0.7109495 ]]) array([[0.61013856]])]
последняя ошибка: [[-0.09273614]]
ошибка: [[-0.00276625]
 [-0.00762292]]
[[-0.          0.00276625  0.00276625]
 [-0.          0.00762292  0.00762292]]


In [193]:
1-0.64207457

0.35792543